{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "harness-ecommerce.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
        - api.{{ .Values.ingress.domain }}
        - admin.{{ .Values.ingress.domain }}
      secretName: {{ include "harness-ecommerce.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "harness-ecommerce.fullname" . }}-web-service
                port:
                  number: 3000
    - host: api.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "harness-ecommerce.fullname" . }}-api-service
                port:
                  number: 8080
    - host: admin.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "harness-ecommerce.fullname" . }}-admin-service
                port:
                  number: 80
{{- end }}
