apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harness-ecommerce.fullname" . }}-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  ConnectionStrings__PostgreSQL: "Host={{ .Values.database.host }};Port={{ .Values.database.port }};Database={{ .Values.database.name }};Username={{ .Values.database.user }};Password={{ .Values.database.password }}"
  RabbitMQ__Username: {{ .Values.rabbitmq.user | quote }}
  RabbitMQ__Password: {{ .Values.rabbitmq.password | quote }}
