<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Harness.$(MSBuildProjectName.Replace('Harness.', ''))</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
