<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Harness.Modules.Catalog\Harness.Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\src\Harness.Modules.Order\Harness.Modules.Order.csproj" />
    <ProjectReference Include="..\..\src\Harness.Modules.Promotion\Harness.Modules.Promotion.csproj" />
    <ProjectReference Include="..\..\src\Harness.Modules.Loyalty\Harness.Modules.Loyalty.csproj" />
    <ProjectReference Include="..\..\src\Harness.Modules.Shipping\Harness.Modules.Shipping.csproj" />
    <ProjectReference Include="..\..\src\Harness.Modules.Payment\Harness.Modules.Payment.csproj" />
    <ProjectReference Include="..\..\src\Harness.Modules.Customer\Harness.Modules.Customer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
