<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Harness.BuildingBlocks.Infrastructure\Harness.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\Harness.BuildingBlocks.Presentation\Harness.BuildingBlocks.Presentation.csproj" />
    <ProjectReference Include="..\Harness.Modules.Order\Harness.Modules.Order.csproj" />
  </ItemGroup>
</Project>
